### ISSUE TITLE
DISPLAY

### ISSUE THREAD

**Issue by paodebatalha** [Euronymou5/FuckYou#1]
Hola amigo, noté que tu script tiene un error que impide ejecutarse en la versión normal de Android Termux, porque la opción de visualización que usa este script no funciona en Phone Termux.

**Comment by Euronymou5** [comment]
> Hola amigo, noté que tu script tiene un error que impide ejecutarse en la versión normal de Android Termux, porque la opción de visualización que usa este script no funciona en Phone Termux.

Puede que sea algo referente a la librería de pyautogui, ya que esta utiliza interfaz gráfica. Aunque en el programa no se utilizan interfaces gráficas, probablemente sea por importar toda la librería. Gracias por reportar el error; hare lo posible por solucionarlo.

**Comment by Euronymou5** [comment]
> Hola amigo, noté que tu script tiene un error que impide ejecutarse en la versión normal de Android Termux, porque la opción de visualización que usa este script no funciona en Phone Termux.

Hola, se sacó una actualización que soluciona el error. Gracias por reportar el error. Saludos.
